// <auto-generated />
using System;
using Grupe_Elevi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Grupe_Elevi.Migrations
{
    [DbContext(typeof(Grupe_EleviContext))]
    [Migration("20210108125530_ClasaElevi")]
    partial class ClasaElevi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Grupe_Elevi.Models.Clasa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeClasa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Clasa");
                });

            modelBuilder.Entity("Grupe_Elevi.Models.ClasaElevi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClasaID")
                        .HasColumnType("int");

                    b.Property<int>("ElevID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClasaID");

                    b.HasIndex("ElevID");

                    b.ToTable("ClasaElevi");
                });

            modelBuilder.Entity("Grupe_Elevi.Models.Elev", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNP")
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("DataNasterii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScoalaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ScoalaID");

                    b.ToTable("Elev");
                });

            modelBuilder.Entity("Grupe_Elevi.Models.Scoala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DenumireScoala")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Scoala");
                });

            modelBuilder.Entity("Grupe_Elevi.Models.ClasaElevi", b =>
                {
                    b.HasOne("Grupe_Elevi.Models.Clasa", "Clasa")
                        .WithMany("ClaseElevi")
                        .HasForeignKey("ClasaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grupe_Elevi.Models.Elev", "Elev")
                        .WithMany("Claselevi")
                        .HasForeignKey("ElevID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Grupe_Elevi.Models.Elev", b =>
                {
                    b.HasOne("Grupe_Elevi.Models.Scoala", "Scoala")
                        .WithMany("Elevi")
                        .HasForeignKey("ScoalaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
